version: 2.1

aliases:
  - &environment
    working_directory: ~/code
    docker:
      - image: cimg/android:2021.10.2
    environment:
      GRADLE_OPTS: '
        -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:MaxPermSize=512m"
        -Dorg.gradle.daemon=false
        -Dorg.gradle.workers.max=3
        -Dkotlin.incremental=false'

jobs:
  "Run_Unit_Test_And_Build":
    <<: *environment
    steps:
      - checkout
      - run:
          name: Write tests variables into local.properties from CI env variables
          command: |
            echo "VAULT_ID=$VAULT_ID" >> local.properties
            echo "JWT_TOKEN_WITHOUT_TRANSFERS=$JWT_TOKEN_WITHOUT_TRANSFERS" >> local.properties
            echo "JWT_TOKEN_WITH_TRANSFERS_WRITE=$JWT_TOKEN_WITH_TRANSFERS_WRITE" >> local.properties
            echo "JWT_TOKEN_WITH_TRANSFERS_ANY=$JWT_TOKEN_WITH_TRANSFERS_ANY" >> local.properties
            echo "AUTHENTICATION_HOST=AUTHENTICATION_HOST" >> local.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "demo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "demo/build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew vgscheckout:lintDebug
      - run:
          name: Run Unit tests
          command: ./gradlew vgscheckout:testDebugUnitTest
      - run:
          name: Generate apk
          command: ./gradlew demo:assembleDebug vgscheckout:assembleDebug vgscheckout:assembleAndroidTest
      - run:
          name: Check if release branch
          command: |
            if [[ $CIRCLE_BRANCH != *"release/"* ]] && [ $CIRCLE_BRANCH != master* ]; then
              echo "Skipped, reason: UI tests should be running only on release branches or master!"
              circleci-agent step halt
            fi
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --app demo/build/outputs/apk/debug/demo-debug.apk \
              --test vgscheckout/build/outputs/apk/androidTest/debug/vgscheckout-debug-androidTest.apk \
              --device model=redfin,version=30,locale=en,orientation=portrait \
workflows:
  main:
    jobs:
      - "Run_Unit_Test_And_Build"