#     TODO: Revert changes after tests
version: 2.1

aliases:
  - &environment
    working_directory: ~/code
    docker:
      - image: cimg/android:2021.10.2
    environment:
      JVM_OPTS: -Xmx4608m

jobs:
  "Run_Unit_Test_And_Build":
    <<: *environment
    steps:
      - checkout
      - run:
          name: Write tests variables into local.properties from CI env variables
          command: |
            echo "VAULT_ID=TEST_VAULT_ID" >> ~/code/local.properties
            echo "JWT_TOKEN_WITHOUT_TRANSFERS=$JWT_TOKEN_WITHOUT_TRANSFERS" >> ~/code/local.properties
            echo "JWT_TOKEN_WITH_TRANSFERS_WRITE=$JWT_TOKEN_WITH_TRANSFERS_WRITE" >> ~/code/local.properties
            echo "JWT_TOKEN_WITH_TRANSFERS_ANY=$JWT_TOKEN_WITH_TRANSFERS_ANY" >> ~/code/local.properties
      - run:
          name: Create google-services.json
          command: |
            echo "Home derictory = ${HOME}"
            echo "GOOGLE_SERVICES_JSON = ${GOOGLE_SERVICES_JSON}"
            echo $GOOGLE_SERVICES_JSON > ${HOME}/vgscheckout/google-services.json
            echo "$(cat ${HOME}/vgscheckout/google-services.json)"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "custom-example/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "custom-example/build.gradle" }}
#      - run:
#          name: Run Lint
#          command: ./gradlew lintDebug
#      - run:
#          name: Run Unit tests
#          command: ./gradlew testDebugUnitTest
      - run:
          name: Generate apk
          command: ./gradlew assembleDebug vgscheckout:assembleDebug vgscheckout:assembleAndroidTest
#      - run:
#          name: Check if release branch
#          command: |
#            if [[ $CIRCLE_BRANCH != *"release/"* ]] && [ $CIRCLE_BRANCH != master* ]; then
#              echo "Skipped, reason: UI tests should be running only on release branches or master!"
#              circleci-agent step halt
#            fi
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --app custom-example/build/outputs/apk/debug/custom-example-debug.apk \
              --test vgscheckout/build/outputs/apk/androidTest/debug/vgscheckout-debug-androidTest.apk \
              --device model=redfin,version=30,locale=en,orientation=portrait \
workflows:
  main:
    jobs:
      - "Run_Unit_Test_And_Build"